"""npm argv-parsing data, GENERATED — do not edit by hand.

Generated from npm 11.8.0 (nopt 9.0.0) by
tests/fixtures/argv_oracles/generate_npm_tables.js; see packagealert/parsers/npm_argv.py.
"""

# Each config key's nopt type: ("single", name) or ("list", (name, ...)). A name is
# a nopt type ("Boolean", "String", "Number", "Array", ...), "null", or "=literal".
NPM_TYPES: dict[str, tuple[str, tuple[str, ...]]] = {
    "_auth": ("list", ("null", "String")),
    "access": ("list", ("null", "=restricted", "=public")),
    "all": ("single", ("Boolean",)),
    "allow-same-version": ("single", ("Boolean",)),
    "also": ("list", ("null", "=dev", "=development")),
    "audit": ("single", ("Boolean",)),
    "audit-level": ("list", ("null", "=info", "=low", "=moderate", "=high", "=critical", "=none")),
    "auth-type": ("list", ("=legacy", "=web")),
    "before": ("list", ("null", "Date")),
    "bin-links": ("single", ("Boolean",)),
    "browser": ("list", ("null", "Boolean", "String")),
    "bypass-2fa": ("single", ("Boolean",)),
    "ca": ("list", ("null", "String", "Array")),
    "cache": ("single", ("path",)),
    "cache-max": ("single", ("Number",)),
    "cache-min": ("single", ("Number",)),
    "cafile": ("single", ("path",)),
    "call": ("single", ("String",)),
    "cert": ("list", ("null", "String")),
    "cidr": ("list", ("null", "String", "Array")),
    "color": ("list", ("=always", "Boolean")),
    "commit-hooks": ("single", ("Boolean",)),
    "cpu": ("list", ("null", "String")),
    "depth": ("list", ("null", "Number")),
    "description": ("single", ("Boolean",)),
    "dev": ("single", ("Boolean",)),
    "diff": ("list", ("String", "Array")),
    "diff-dst-prefix": ("single", ("String",)),
    "diff-ignore-all-space": ("single", ("Boolean",)),
    "diff-name-only": ("single", ("Boolean",)),
    "diff-no-prefix": ("single", ("Boolean",)),
    "diff-src-prefix": ("single", ("String",)),
    "diff-text": ("single", ("Boolean",)),
    "diff-unified": ("single", ("Number",)),
    "dry-run": ("single", ("Boolean",)),
    "editor": ("single", ("String",)),
    "engine-strict": ("single", ("Boolean",)),
    "expect-result-count": ("list", ("null", "Number")),
    "expect-results": ("list", ("null", "Boolean")),
    "expires": ("list", ("null", "Number")),
    "fetch-retries": ("single", ("Number",)),
    "fetch-retry-factor": ("single", ("Number",)),
    "fetch-retry-maxtimeout": ("single", ("Number",)),
    "fetch-retry-mintimeout": ("single", ("Number",)),
    "fetch-timeout": ("single", ("Number",)),
    "force": ("single", ("Boolean",)),
    "foreground-scripts": ("single", ("Boolean",)),
    "format-package-lock": ("single", ("Boolean",)),
    "fund": ("single", ("Boolean",)),
    "git": ("single", ("String",)),
    "git-tag-version": ("single", ("Boolean",)),
    "global": ("single", ("Boolean",)),
    "global-style": ("single", ("Boolean",)),
    "globalconfig": ("single", ("path",)),
    "heading": ("single", ("String",)),
    "https-proxy": ("list", ("null", "url")),
    "if-present": ("single", ("Boolean",)),
    "ignore-scripts": ("single", ("Boolean",)),
    "include": ("list", ("Array", "=prod", "=dev", "=optional", "=peer")),
    "include-staged": ("single", ("Boolean",)),
    "include-workspace-root": ("single", ("Boolean",)),
    "init-author-email": ("single", ("String",)),
    "init-author-name": ("single", ("String",)),
    "init-author-url": ("list", ("=", "url")),
    "init-license": ("single", ("String",)),
    "init-module": ("single", ("path",)),
    "init-private": ("single", ("Boolean",)),
    "init-type": ("single", ("String",)),
    "init-version": ("single", ("semver",)),
    "init.author.email": ("single", ("String",)),
    "init.author.name": ("single", ("String",)),
    "init.author.url": ("list", ("=", "url")),
    "init.license": ("single", ("String",)),
    "init.module": ("single", ("path",)),
    "init.version": ("single", ("semver",)),
    "install-links": ("single", ("Boolean",)),
    "install-strategy": ("list", ("=hoisted", "=nested", "=shallow", "=linked")),
    "json": ("single", ("Boolean",)),
    "key": ("list", ("null", "String")),
    "legacy-bundling": ("single", ("Boolean",)),
    "legacy-peer-deps": ("single", ("Boolean",)),
    "libc": ("list", ("null", "String")),
    "link": ("single", ("Boolean",)),
    "local-address": ("list", ("null", "String")),
    "location": ("list", ("=global", "=user", "=project")),
    "lockfile-version": ("list", ("null", "other", "other", "other", "=1", "=2", "=3")),
    "loglevel": ("list", ("=silent", "=error", "=warn", "=notice", "=http", "=info", "=verbose", "=silly")),
    "logs-dir": ("list", ("null", "path")),
    "logs-max": ("single", ("Number",)),
    "long": ("single", ("Boolean",)),
    "maxsockets": ("single", ("Number",)),
    "message": ("single", ("String",)),
    "name": ("list", ("null", "String")),
    "node-gyp": ("single", ("path",)),
    "node-options": ("list", ("null", "String")),
    "noproxy": ("list", ("String", "Array")),
    "offline": ("single", ("Boolean",)),
    "omit": ("list", ("Array", "=dev", "=optional", "=peer")),
    "omit-lockfile-registry-resolved": ("single", ("Boolean",)),
    "only": ("list", ("null", "=prod", "=production")),
    "optional": ("list", ("null", "Boolean")),
    "orgs": ("list", ("null", "String", "Array")),
    "orgs-permission": ("list", ("null", "=read-only", "=read-write", "=no-access")),
    "os": ("list", ("null", "String")),
    "otp": ("list", ("null", "String")),
    "pack-destination": ("single", ("String",)),
    "package": ("list", ("String", "Array")),
    "package-lock": ("single", ("Boolean",)),
    "package-lock-only": ("single", ("Boolean",)),
    "packages": ("list", ("null", "String", "Array")),
    "packages-all": ("single", ("Boolean",)),
    "packages-and-scopes-permission": ("list", ("null", "=read-only", "=read-write", "=no-access")),
    "parseable": ("single", ("Boolean",)),
    "password": ("list", ("null", "String")),
    "prefer-dedupe": ("single", ("Boolean",)),
    "prefer-offline": ("single", ("Boolean",)),
    "prefer-online": ("single", ("Boolean",)),
    "prefix": ("single", ("path",)),
    "preid": ("single", ("String",)),
    "production": ("list", ("null", "Boolean")),
    "progress": ("single", ("Boolean",)),
    "provenance": ("single", ("Boolean",)),
    "provenance-file": ("single", ("path",)),
    "proxy": ("list", ("null", "other", "url")),
    "read-only": ("single", ("Boolean",)),
    "rebuild-bundle": ("single", ("Boolean",)),
    "registry": ("single", ("url",)),
    "replace-registry-host": ("list", ("=npmjs", "=never", "=always", "String")),
    "save": ("single", ("Boolean",)),
    "save-bundle": ("single", ("Boolean",)),
    "save-dev": ("single", ("Boolean",)),
    "save-exact": ("single", ("Boolean",)),
    "save-optional": ("single", ("Boolean",)),
    "save-peer": ("single", ("Boolean",)),
    "save-prefix": ("single", ("String",)),
    "save-prod": ("single", ("Boolean",)),
    "sbom-format": ("list", ("=cyclonedx", "=spdx")),
    "sbom-type": ("list", ("=library", "=application", "=framework")),
    "scope": ("single", ("String",)),
    "scopes": ("list", ("null", "String", "Array")),
    "script-shell": ("list", ("null", "String")),
    "searchexclude": ("single", ("String",)),
    "searchlimit": ("single", ("Number",)),
    "searchopts": ("single", ("String",)),
    "searchstaleness": ("single", ("Number",)),
    "shell": ("single", ("String",)),
    "shrinkwrap": ("single", ("Boolean",)),
    "sign-git-commit": ("single", ("Boolean",)),
    "sign-git-tag": ("single", ("Boolean",)),
    "strict-peer-deps": ("single", ("Boolean",)),
    "strict-ssl": ("single", ("Boolean",)),
    "tag": ("single", ("String",)),
    "tag-version-prefix": ("single", ("String",)),
    "timing": ("single", ("Boolean",)),
    "token-description": ("list", ("null", "String")),
    "umask": ("single", ("Umask",)),
    "unicode": ("single", ("Boolean",)),
    "update-notifier": ("single", ("Boolean",)),
    "usage": ("single", ("Boolean",)),
    "user-agent": ("single", ("String",)),
    "userconfig": ("single", ("path",)),
    "version": ("single", ("Boolean",)),
    "versions": ("single", ("Boolean",)),
    "viewer": ("single", ("String",)),
    "which": ("list", ("null", "Number")),
    "workspace": ("list", ("String", "Array")),
    "workspaces": ("list", ("null", "Boolean")),
    "workspaces-update": ("single", ("Boolean",)),
    "yes": ("list", ("null", "Boolean")),
}
NPM_SHORTHANDS: dict[str, tuple[str, ...]] = {
    "?": ("--usage",),
    "B": ("--save-bundle",),
    "C": ("--prefix",),
    "D": ("--save-dev",),
    "E": ("--save-exact",),
    "H": ("--usage",),
    "L": ("--location",),
    "O": ("--save-optional",),
    "P": ("--save-prod",),
    "S": ("--save",),
    "a": ("--all",),
    "c": ("--call",),
    "d": ("--loglevel", "info"),
    "dd": ("--loglevel", "verbose"),
    "ddd": ("--loglevel", "silly"),
    "desc": ("--description",),
    "enjoy-by": ("--before",),
    "f": ("--force",),
    "g": ("--global",),
    "h": ("--usage",),
    "help": ("--usage",),
    "iwr": ("--include-workspace-root",),
    "l": ("--long",),
    "local": ("--no-global",),
    "m": ("--message",),
    "n": ("--no-yes",),
    "no": ("--no-yes",),
    "p": ("--parseable",),
    "porcelain": ("--parseable",),
    "q": ("--loglevel", "warn"),
    "quiet": ("--loglevel", "warn"),
    "readonly": ("--read-only",),
    "reg": ("--registry",),
    "s": ("--loglevel", "silent"),
    "silent": ("--loglevel", "silent"),
    "v": ("--version",),
    "verbose": ("--loglevel", "verbose"),
    "w": ("--workspace",),
    "ws": ("--workspaces",),
    "y": ("--yes",),
}
NPM_COMMANDS: tuple[str, ...] = ("access", "adduser", "audit", "bugs", "cache", "ci", "completion", "config", "dedupe", "deprecate", "diff", "dist-tag", "docs", "doctor", "edit", "exec", "explain", "explore", "find-dupes", "fund", "get", "help", "help-search", "init", "install", "install-ci-test", "install-test", "link", "ll", "login", "logout", "ls", "org", "outdated", "owner", "pack", "ping", "pkg", "prefix", "profile", "prune", "publish", "query", "rebuild", "repo", "restart", "root", "run", "sbom", "search", "set", "shrinkwrap", "star", "stars", "start", "stop", "team", "test", "token", "undeprecate", "uninstall", "unpublish", "unstar", "update", "version", "view", "whoami")
NPM_COMMAND_ALIASES: dict[str, str] = {
    "add": "install",
    "add-user": "adduser",
    "author": "owner",
    "c": "config",
    "cit": "install-ci-test",
    "clean-install": "ci",
    "clean-install-test": "install-ci-test",
    "create": "init",
    "ddp": "dedupe",
    "dist-tags": "dist-tag",
    "find": "search",
    "hlep": "help",
    "home": "docs",
    "i": "install",
    "ic": "ci",
    "in": "install",
    "info": "view",
    "innit": "init",
    "ins": "install",
    "inst": "install",
    "insta": "install",
    "instal": "install",
    "install-clean": "ci",
    "isnt": "install",
    "isnta": "install",
    "isntal": "install",
    "isntall": "install",
    "isntall-clean": "ci",
    "issues": "bugs",
    "it": "install-test",
    "la": "ll",
    "list": "ls",
    "ln": "link",
    "ogr": "org",
    "r": "uninstall",
    "rb": "rebuild",
    "remove": "uninstall",
    "rm": "uninstall",
    "rum": "run",
    "run-script": "run",
    "s": "search",
    "se": "search",
    "show": "view",
    "sit": "install-ci-test",
    "t": "test",
    "tst": "test",
    "udpate": "update",
    "un": "uninstall",
    "unlink": "uninstall",
    "up": "update",
    "upgrade": "update",
    "urn": "run",
    "v": "view",
    "verison": "version",
    "why": "explain",
    "x": "exec",
}
